application: new-project-template
version: 1
runtime: python27
api_version: 1
#threadsafe: yes
threadsafe: no

handlers:
- url: /load
  script: loader.py
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /default\.css
  static_files: default.css
  upload: default\.css

- url: /markers
  script: markers.py
#  static_files: marinas.json
#  upload: marinas\.json

- url: /
  static_files: marinas.html
  upload: marinas\.html
 
libraries:
- name: webapp2
  version: "2.5.1"
